class PartnerPreferenceConstData {
  static const List<String> educationList = [
    '10th',
    '12th',
    'Secondary School',
    'Bachelor\'s Degree',
    'BCA',
    'B.Sc. IT/Computer Science',
    'B.Tech',
    'B.E',
    'B.Arch',
    'Aeronautical Engineering',
    'B.Plan',
    'B.Sc.',
    'B.S.W',
    'B.Phil.',
    'B.M.M.',
    'BFA',
    'BFT',
    'BLIS',
    'B.H.M.',
    'BHA / BHM (Hospital Administration)',
    'Other Bachelor Degree in Engineering / Computers',
    'Other Bachelor Degree in Arts / Science / Commerce',
    'Other Bachelor Degree in Management',
    'Other Bachelor Degree in Legal',
    'Other Bachelor Degree in Medicine',
    'Master\'s Degree',
    'MCA',
    'M.Tech',
    'M.Sc. IT/Computer Science',
    'M.S.(Engg.)',
    'M.Arch.',
    'MFA',
    'M.Ed.',
    'MSc',
    'M.Phil.',
    'M.Com',
    'MSW',
    'MHA / MHM (Hospital Administration)',
    'MFM (Financial Management)',
    'MHM  (Hotel Management)',
    'MHRM (Human Resource Management)',
    'PGDM',
    'Other Master Degree in Engineering / Computers',
    'Other Master Degree in Arts / Science / Commerce',
    'Other Master Degree in Management',
    'Other Master Degree in Medicine',
    'Other Master Degree in Legal',
    'Ph.D.',
    'DM',
    'Postdoctoral fellow',
    'Fellow of National Board (FNB)',
    'Vocational Training',
    'Technical Certification',
    'Online Courses',
    'Diploma',
    'Polytechnic',
    'Trade School',
    'Others in Diploma',
    'Other Degree in Finance',
    'CA',
    'CFA (Chartered Financial Analyst)',
    'CS',
    'ICWA',
    'IAS',
    'IES',
    'IFS',
    'IRS',
    'IPS',
    'Other Degree in Service',
    'B.A.M.S.',
    'BDS',
    'BHMS',
    'BSMS',
    'BUMS',
    'BVSc',
    'MBBS',
    'MDS',
    'MD / MS (Medical)',
    'MVSc',
    'MCh',
    'DNB',
    'BPharm',
    'BPT',
    'B.Sc. Nursing',
    'M.Pharm',
    'MPT',
    'Other'
  ];

  static const List<String> employedInList = [
    'Government',
    'Private',
    'Business',
    'Self-employed',
    'Freelancer',
    'Non-profit Organization',
    'NGO',
    'Start-up',
    'Multinational Corporation',
    'Startup',
    'Public Sector',
    'Healthcare',
    'Educational Institution',
    'Research Organization',
    'Consultancy',
    'Other'
  ];

  static const List<String> occupationList = [
    'Engineer',
    'Doctor',
    'Teacher',
    'Business Analyst',
    'Software Developer',
    'Nurse',
    'Architect',
    'Scientist',
    'Accountant',
    'Lawyer',
    'Teacher',
    'Marketing Manager',
    'Data Analyst',
    'HR Manager',
    'Project Manager',
  ];

  static const List<String> occupationListPreference = [
    'Software Professional',
    'Engineer',
    'Doctor',
    'Teacher',
    'Business Owner',
    'Accountant',
    'Lawyer',
    'Architect',
    'Consultant',
    'Artist',
    'Writer',
    'Sales Professional',
    'Marketing Professional',
    'Healthcare Worker',
    'Other',
  ];

  static const List<String> incomeList = [
    '₹ 1 lakh & below',
    '₹ 1 lakh - ₹ 2 lakh',
    '₹ 2 lakh - ₹ 3 lakh',
    '₹ 3 lakh - ₹ 5 lakh',
    '₹ 5 lakh - ₹ 7 lakh',
    '₹ 7 lakh - ₹ 10 lakh',
    '₹ 10 lakh - ₹ 15 lakh',
    '₹ 15 lakh - ₹ 20 lakh',
    '₹ 20 lakh - ₹ 30 lakh',
    '₹ 30 lakh - ₹ 40 lakh',
    '₹ 40 lakh - ₹ 50 lakh',
    '₹ 50 lakh & above',
  ];
  static const List<String> toAgeList = [
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
  ];

  static List<String> weightListPartner = [
    for (int i = 45; i <= 120; i++) i.toString(),
  ];

  static const List<String> starList = [
    'Ashwini (அஸ்வினி)',
    'Bharani (பரணி)',
    'Krittika (கிருத்திகை)',
    'Rohini (ரோகிணி)',
    'Mrigashira (மிருகசீரிடம்)',
    'Ardra (திருவாதிரை)',
    'Punarvasu (புனர்பூசம்)',
    'Pushya (பூசம்)',
    'Ashlesha (ஆயில்யம்)',
    'Magha (மகம்)',
    'Purva Phalguni (பூரம்)',
    'Uttara Phalguni (உத்திரம்)',
    'Hasta (அஸ்தம்)',
    'Chitra (சித்திரை)',
    'Swati (ஸ்வாதி)',
  ];

  static const List<String> raasiList = [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces"
  ];

  static const List<String> weightList = [
    '30 - 40 kg',
    '40 - 50 kg',
    '50 - 60 kg',
    '60 - 70 kg',
    '70 - 80 kg',
    '80 - 90 kg',
    '90 - 100 kg',
    '100 - 110 kg',
    '110 - 120 kg',
    '120 - 130 kg',
    '130 - 140 kg',
    '140 - 150 kg',
  ];

  static var myHeightOptions = {
    0: '4 ft 6 in (137 cm)',
    1: '4 ft 7 in (139 cm)',
    2: '4 ft 8 in (142 cm)',
    3: '4 ft 9 in (144 cm)',
    4: '4 ft 10 in (147 cm)',
    5: '5 ft (149 cm)',
    6: '5 ft 1 in (152 cm)',
    7: '5 ft 2 in (154 cm)',
    8: '5 ft 3 in (157 cm)',
    9: '5 ft 4 in (160 cm)',
    10: '5 ft 5 in (163 cm)',
    11: '5 ft 6 in (167 cm)',
    12: '5 ft 7 in (170 cm)',
    13: '5 ft 8 in (173 cm)',
    14: '5 ft 9 in (175 cm)',
    15: '5 ft 10 in (178 cm)',
    16: '5 ft 11 in (180 cm)',
    17: '6 ft (183 cm)',
    18: '6 ft 1 in (185 cm)',
    19: '6 ft 2 in (188 cm)',
    20: '6 ft 3 in (190 cm)',
    21: '6 ft 4 in (193 cm)',
    22: '6 ft 5 in (196 cm)',
    23: '6 ft 6 in (198 cm)',
    24: '6 ft 7 in (201 cm)',
    25: '6 ft 8 in (203 cm)',
    26: '6 ft 9 in (206 cm)',
  };

  static const List<String> maritalStatusOptions = [
    'Never Married',
    'Widow',
    'divorced',
    'Awaiting Divorce'
  ];

  static const List<String> physicalStatusOptions = [
    'Normal',
    'Physically Challenged',
    'Doesn’t Matter'
  ];
  static const List<String> eatingHabitsOptions = [
    'Doesn’t Matter',
    'Vegetarian',
    'Non - Vegetarian',
    'Eggetarian'
  ];

  static const List<String> drinkingHabitsOptions = [
    'Doesn’t Matter',
    'Never Drinks',
    'Drinks Socially',
    'Drinks Regularly'
  ];

  static const List<String> smokingHabitsOptions = [
    'Doesn’t Matter',
    'Never Smokes',
    'Smokes Occasionally',
    'Smokes Regularly'
  ];

  static const List<String> motherTongueOptions = [
    'Hindi',
    'English',
    'Tamil',
    'Telugu',
    'Malayalam',
    'Kannada',
    'Bengali',
    'Marathi',
    'Gujarati',
    'Punjabi',
    'Urdu',
    'Assamese',
    'Odia',
    'Maithili',
    'Sanskrit',
    'Dogri',
    'Manipuri',
    'Bodo',
    'Konkani',
    'Sindhi',
    'Nepali',
    'Santali',
    'Kashmiri',
    'Kurigram',
    'Mizo',
    'Haryanvi',
    'Rajasthani',
    'Angika',
    'Chhattisgarhi',
    'Bhili/Bhilodi',
    'Marwari',
    'Tulu',
    'Garhwali',
    'Kumaoni',
    'Khandeshi',
    'Khasi',
    'Lepcha',
    'Sikkimese',
    'Other'
  ];

  static const List<String> religionOptions = [
    'Hindu',
    'Muslim',
    'Christian',
    'Sikh',
    'Buddhist',
    'Jain',
    'Jewish',
    'Parsi',
    'Other',
    'Zoroastrian',
    'Bahá\'í',
    'Atheist',
    'Spiritual but not religious',
    'Animism',
    'Confucianism',
    'Taoism',
    'Shinto',
    'Rastafari',
    'Wicca'
  ];

  static const List<String> casteOptions = [
    'Brahmin',
    'Kshatriya',
    'Vaishya',
    'Shudra',
    'Scheduled Castes (SC)',
    'Scheduled Tribes (ST)',
    'Other Backward Classes (OBC)',
    'Jat',
    'Yadav',
    'Rajput',
    'Maratha',
    'Vokkaliga',
    'Baniya',
    'Kayastha',
    'Kurmi',
    'Patel',
    'Nair',
    'Iyer',
    'Iyyer',
    'Sindhi',
    'Mahar',
    'Madhesi',
    'Lohar',
    'Meena',
    'Gupta',
    'Gujjars',
    'Teli',
    'Jain',
    'Musalman (Muslim)',
    'Parsi',
    'Ravidasia',
    'Bauri',
    'Mochi',
    'Dom',
    'Kalar',
    'Koli',
    'Reddy',
    'Kumbhakar',
    'Chamar',
    'Saini',
    'Bauri',
    'Sikh',
    'Vishwakarma',
    'Chandravanshi',
    'Maithil',
    'Bodo',
    'Gorkha',
    'Naga',
    'Lambani',
    'Chaudhary',
    'Vanniyar',
    'Ravidasia',
    'Gond',
    'Pasi',
    'Dhangar',
    'Banjara',
    'Thakur',
    'Mushar',
    'Ghosi'
  ];

  static const List<String> subCasteOptions = [
    'Sub Caste 1',
    'Sub Caste 2',
    'Sub Caste 3',
    'Others'
  ];

  static const List<String> educationData = [
    '10th',
    '12th',
    'Secondary School',
    'Bachelor\'s Degree',
    'BCA',
    'B.Sc. IT/Computer Science',
    'B.Tech',
    'B.E',
    'B.Arch',
    'Aeronautical Engineering',
    'B.Plan',
    'B.Sc.',
    'B.S.W',
    'B.Phil.',
    'B.M.M.',
    'BFA',
    'BFT',
    'BLIS',
    'B.H.M.',
    'BHA / BHM (Hospital Administration)',
    'Other Bachelor Degree in Engineering / Computers',
    'Other Bachelor Degree in Arts / Science / Commerce',
    'Other Bachelor Degree in Management',
    'Other Bachelor Degree in Legal',
    'Other Bachelor Degree in Medicine',
    'Master\'s Degree',
    'MCA',
    'M.Tech',
    'M.Sc. IT/Computer Science',
    'M.S.(Engg.)',
    'M.Arch.',
    'MFA',
    'M.Ed.',
    'MSc',
    'M.Phil.',
    'M.Com',
    'MSW',
    'MHA / MHM (Hospital Administration)',
    'MFM (Financial Management)',
    'MHM  (Hotel Management)',
    'MHRM (Human Resource Management)',
    'PGDM',
    'Other Master Degree in Engineering / Computers',
    'Other Master Degree in Arts / Science / Commerce',
    'Other Master Degree in Management',
    'Other Master Degree in Medicine',
    'Other Master Degree in Legal',
    'Ph.D.',
    'DM',
    'Postdoctoral fellow',
    'Fellow of National Board (FNB)',
    'Vocational Training',
    'Technical Certification',
    'Online Courses',
    'Diploma',
    'Polytechnic',
    'Trade School',
    'Others in Diploma',
    'Other Degree in Finance',
    'CA',
    'CFA (Chartered Financial Analyst)',
    'CS',
    'ICWA',
    'IAS',
    'IES',
    'IFS',
    'IRS',
    'IPS',
    'Other Degree in Service',
    'B.A.M.S.',
    'BDS',
    'BHMS',
    'BSMS',
    'BUMS',
    'BVSc',
    'MBBS',
    'MDS',
    'MD / MS (Medical)',
    'MVSc',
    'MCh',
    'DNB',
    'BPharm',
    'BPT',
    'B.Sc. Nursing',
    'M.Pharm',
    'MPT',
    'Other'
  ];

  static const List<String> employmentOptions = [
    'Private Sector',
    'Public Sector',
    'Business Owner',
    'Self Employed',
    'Freelancer',
    'Not Working',
  ];

  static const List<String> occupationOptions = [
    'Software Engineer',
    'Doctor',
    'Teacher',
    'Lawyer',
    'Business Person',
    'Other',
  ];

  static const List<String> currencyOptions = [
    'INR (₹)',
    'USD (\$)',
    'EUR (€)',
    'GBP (£)',
    'AED (د.إ)',
  ];

  static const Map<String, List<String>> incomeRangeOptions = {
    'INR (₹)': [
      '₹ 1 lakh & below',
      '₹ 1 lakh - ₹ 2 lakh',
      '₹ 2 lakh - ₹ 3 lakh',
      '₹ 3 lakh - ₹ 5 lakh',
      '₹ 5 lakh - ₹ 7 lakh',
      '₹ 7 lakh - ₹ 10 lakh',
      '₹ 10 lakh - ₹ 15 lakh',
      '₹ 15 lakh - ₹ 20 lakh',
      '₹ 20 lakh - ₹ 30 lakh',
      '₹ 30 lakh - ₹ 40 lakh',
      '₹ 40 lakh - ₹ 50 lakh',
      '₹ 50 lakh & above',
    ],
    'USD (\$)': [
      'Less than 4,000',
      '4,000-7,000',
      '7,000-10,000',
      '10,000-15,000',
      '15,000-20,000',
      'More than 20,000',
    ],
    'EUR (€)': [
      'Less than 3,500',
      '3,500-6,000',
      '6,000-8,000',
      '8,000-12,000',
      '12,000-15,000',
      'More than 15,000',
    ],
    'GBP (£)': [
      'Less than 3,000',
      '3,000-5,500',
      '5,500-8,000',
      '8,000-12,000',
      '12,000-15,000',
      'More than 15,000',
    ],
    'AED (د.إ)': [
      'Less than 10,000',
      '10,000-15,000',
      '15,000-20,000',
      '20,000-30,000',
      '30,000-40,000',
      'More than 40,000',
    ],
  };

  static const List<String> countries = [
    'India',
    'United States',
    'Canada',
  ];

  static const Map<String, List<String>> states = {
    'India': ['Maharashtra', 'Karnataka', 'Tamil Nadu'],
    'United States': ['California', 'Texas', 'New York'],
    'Canada': ['Ontario', 'Quebec', 'British Columbia'],
  };

  static const Map<String, List<String>> cities = {
    'Maharashtra': ['Mumbai', 'Pune', 'Nagpur'],
    'Karnataka': ['Bengaluru', 'Mysuru', 'Mangalore'],
    'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai'],
    'California': ['Los Angeles', 'San Francisco', 'San Diego'],
    'Texas': ['Houston', 'Dallas', 'Austin'],
    'New York': ['New York City', 'Buffalo', 'Rochester'],
    'Ontario': ['Toronto', 'Ottawa', 'Hamilton'],
    'Quebec': ['Montreal', 'Quebec City', 'Laval'],
    'British Columbia': ['Vancouver', 'Victoria', 'Surrey'],
  };
}
