class PartnerPreferenceConstData {
  static const List<String> toAgeList = [
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
  ];

  static var myHeightOptions = {
    0: '4 ft 6 in (137 cm)',
    1: '4 ft 7 in (139 cm)',
    2: '4 ft 8 in (142 cm)',
    3: '4 ft 9 in (144 cm)',
    4: '4 ft 10 in (147 cm)',
    5: '5 ft (149 cm)',
    6: '5 ft 1 in (152 cm)',
    7: '5 ft 2 in (154 cm)',
    8: '5 ft 3 in (157 cm)',
    9: '5 ft 4 in (160 cm)',
    10: '5 ft 5 in (163 cm)',
    11: '5 ft 6 in (167 cm)',
    12: '5 ft 7 in (170 cm)',
    13: '5 ft 8 in (173 cm)',
    14: '5 ft 9 in (175 cm)',
    15: '5 ft 10 in (178 cm)',
    16: '5 ft 11 in (180 cm)',
    17: '6 ft (183 cm)',
    18: '6 ft 1 in (185 cm)',
    19: '6 ft 2 in (188 cm)',
    20: '6 ft 3 in (190 cm)',
    21: '6 ft 4 in (193 cm)',
    22: '6 ft 5 in (196 cm)',
    23: '6 ft 6 in (198 cm)',
    24: '6 ft 7 in (201 cm)',
    25: '6 ft 8 in (203 cm)',
    26: '6 ft 9 in (206 cm)',
  };
  static const List<String> maritalStatusOptions = [
    'Never Married',
    'Divorced',
    'Widowed',
    'Separated'
  ];

  static const List<String> physicalStatusOptions = [
    'Normal',
    'Physically Challenged'
  ];
  static const List<String> eatingHabitsOptions = [
    'Vegetarian',
    'Non-Vegetarian',
    'Eggetarian',
    'Vegan'
  ];
  static const List<String> drinkingHabitsOptions = [
    'No',
    'Occasionally',
    'Yes'
  ];
  static const List<String> smokingHabitsOptions = [
    'No',
    'Occasionally',
    'Yes'
  ];

  static const List<String> motherTongueOptions = [
    'Hindi',
    'English',
    'Tamil',
    'Telugu',
    'Malayalam',
    'Kannada',
    'Bengali',
    'Marathi',
    'Gujarati',
    'Punjabi',
    'Urdu',
    'Assamese',
    'Odia',
    'Maithili',
    'Sanskrit',
    'Dogri',
    'Manipuri',
    'Bodo',
    'Konkani',
    'Sindhi',
    'Nepali',
    'Santali',
    'Kashmiri',
    'Kurigram',
    'Mizo',
    'Haryanvi',
    'Rajasthani',
    'Angika',
    'Chhattisgarhi',
    'Bhili/Bhilodi',
    'Marwari',
    'Tulu',
    'Garhwali',
    'Kumaoni',
    'Khandeshi',
    'Khasi',
    'Lepcha',
    'Sikkimese'
  ];

  static const List<String> religionOptions = [
    'Hindu',
    'Muslim',
    'Christian',
    'Sikh',
    'Buddhist',
    'Jain',
    'Jewish',
    'Parsi',
    'Other',
    'Zoroastrian',
    'Bahá\'í',
    'Atheist',
    'Spiritual but not religious',
    'Animism',
    'Confucianism',
    'Taoism',
    'Shinto',
    'Rastafari',
    'Wicca'
  ];

  static const List<String> casteOptions = [
    'Brahmin',
    'Kshatriya',
    'Vaishya',
    'Shudra',
    'Scheduled Castes (SC)',
    'Scheduled Tribes (ST)',
    'Other Backward Classes (OBC)',
    'Jat',
    'Yadav',
    'Rajput',
    'Maratha',
    'Vokkaliga',
    'Baniya',
    'Kayastha',
    'Kurmi',
    'Patel',
    'Nair',
    'Iyer',
    'Iyyer',
    'Sindhi',
    'Mahar',
    'Madhesi',
    'Lohar',
    'Meena',
    'Gupta',
    'Gujjars',
    'Teli',
    'Jain',
    'Musalman (Muslim)',
    'Parsi',
    'Ravidasia',
    'Bauri',
    'Mochi',
    'Dom',
    'Kalar',
    'Koli',
    'Reddy',
    'Kumbhakar',
    'Chamar',
    'Saini',
    'Bauri',
    'Sikh',
    'Vishwakarma',
    'Chandravanshi',
    'Maithil',
    'Bodo',
    'Gorkha',
    'Naga',
    'Lambani',
    'Chaudhary',
    'Vanniyar',
    'Ravidasia',
    'Gond',
    'Pasi',
    'Dhangar',
    'Banjara',
    'Thakur',
    'Mushar',
    'Ghosi'
  ];

  static const List<String> subCasteOptions = [
    'Sub Caste 1',
    'Sub Caste 2',
    'Sub Caste 3',
    'Others'
  ];
}
