name: matrimony
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^1.0.0
  flutter_riverpod: ^2.6.0
  http:
  shared_preferences:
  image_picker:
  permission_handler: ^11.3.1
  razorpay_flutter: ^1.3.7
  fluttertoast: ^8.2.4
  equatable:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.25
  skeletonizer:
  url_launcher:
  geolocator:
  geocoding:
  intl:
  flutter_native_splash:
  connectivity_plus: ^4.0.2
  carousel_slider: ^5.0.0
  rename_app: ^1.6.1
  dotted_border:
  hive:
  hive_generator:
  firebase_core:
  firebase_messaging:
  awesome_notifications: ^0.9.3+1
  path_provider:
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  intl:

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/image/
     - assets/image/emptyProfile.png

  fonts:
     - family: Michroma
       fonts:
         - asset: fonts/Michroma-Regular.ttf

flutter_native_splash:
  color: "#ffffff" # Splash screen background color
  image: "assets/image/astro_logo.png" # Splash screen logo
  android: true
  ios: true
  web: true