// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjQooPvpgi6Xp3ZQcJgYGsf-zu6Z4XPu8',
    appId: '1:769129959135:web:7c6fdb8004f43fc99da36a',
    messagingSenderId: '769129959135',
    projectId: 'ahathirumanam',
    authDomain: 'ahathirumanam.firebaseapp.com',
    storageBucket: 'ahathirumanam.firebasestorage.app',
    measurementId: 'G-20J774PWVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRunW1rKysGhJPe4n3U4au7Txw48t-jSI',
    appId: '1:769129959135:android:4fc17149c8f38b8a9da36a',
    messagingSenderId: '769129959135',
    projectId: 'ahathirumanam',
    storageBucket: 'ahathirumanam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDngZgIESAAuIS5Wa9gB0xdQ1M3oOb-gQ8',
    appId: '1:769129959135:ios:5ba06d5890392cf99da36a',
    messagingSenderId: '769129959135',
    projectId: 'ahathirumanam',
    storageBucket: 'ahathirumanam.firebasestorage.app',
    iosBundleId: 'com.example.matrimony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDngZgIESAAuIS5Wa9gB0xdQ1M3oOb-gQ8',
    appId: '1:769129959135:ios:5ba06d5890392cf99da36a',
    messagingSenderId: '769129959135',
    projectId: 'ahathirumanam',
    storageBucket: 'ahathirumanam.firebasestorage.app',
    iosBundleId: 'com.example.matrimony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjQooPvpgi6Xp3ZQcJgYGsf-zu6Z4XPu8',
    appId: '1:769129959135:web:6b3708c5acb8c7a09da36a',
    messagingSenderId: '769129959135',
    projectId: 'ahathirumanam',
    authDomain: 'ahathirumanam.firebaseapp.com',
    storageBucket: 'ahathirumanam.firebasestorage.app',
    measurementId: 'G-7T9VMQGPK2',
  );
}
